@startuml
hide circle
skinparam classAttributeIconSize 0

Class "{abstract}\nCommand" as Command {
  +execute(Model): CommandResult
}
Class RemarkCommand {
  +COMMAND_WORD: String
  +MESSAGE_USAGE: String
  +MESSAGE_NOT_IMPLEMENTED_YET: String
  +MESSAGE_SUCCESS: String
  +MESSAGE_DUPLICATE_REMARK: String
  +execute(Model): CommandResult
}
Class CommandException

RemarkCommand -up-|> Command
Command ..> CommandException: throws >
RemarkCommand .right.> CommandException: throws >
@enduml
