ignore:
  - "src/main/java/spleetwaise/commons/ui/*"
  - "src/main/java/spleetwaise/address/ui/*"
  - "src/main/java/spleetwaise/transaction/ui/*"
  - "src/main/java/spleetwaise/commons/MainApp.java"
