@startuml
!include ../style.puml
skinparam ArrowFontStyle plain

title MarkLessonAttendanceCommand Sequence Diagram

box Logic LOGIC_COLOR_T1
participant ":MarkLessonAttendanceCommand" as command LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as model MODEL_COLOR
participant ":Lesson" as lesson MODEL_COLOR_T2
end box

[-> command : execute(model)
activate command LOGIC_COLOR
command -[MODEL_COLOR]> model : getFilteredLessonList()
activate model MODEL_COLOR

model --[MODEL_COLOR]> command : list of lessons
deactivate model

create lesson
command -[LOGIC_COLOR]> lesson : new Lesson(targetLesson)
activate lesson MODEL_COLOR_T2

lesson --[LOGIC_COLOR]> command
deactivate lesson MODEL_COLOR_T2

box ModelLoop
loop for each student
    command -[MODEL_COLOR]> model : findStudentByName(studentName)
    activate model MODEL_COLOR

    model --[MODEL_COLOR]> command : student
    deactivate model

    command -[LOGIC_COLOR]> lesson : setAttendance(student, attendance)
    activate lesson MODEL_COLOR_T2
    lesson --[LOGIC_COLOR]> command :
    deactivate lesson
end
end box

command -[MODEL_COLOR]> model : setLesson(targetLesson, newLesson)
activate model MODEL_COLOR

model --[MODEL_COLOR]> command
deactivate model

[<--command : CommandResult
deactivate command LOGIC_COLOR

@enduml
