@startuml
'https://plantuml.com/class-diagram

abstract Command {
    execute()
}
abstract AbstractEditCommand {
    -index
    -editPersonDescriptor
}
class EditCommand
class AddPublicAddressCommand
class DeletePublicAddressCommand
Command <|-- AbstractEditCommand
AbstractEditCommand <|- EditCommand
AddPublicAddressCommand -|> AbstractEditCommand
AbstractEditCommand <|-- DeletePublicAddressCommand

@enduml
