@startuml
!include style.puml
skinparam ArrowFontStyle plain

Actor user as user USER_COLOR

box Logic LOGIC_COLOR_T1
participant "LogicManager" as Logic LOGIC_COLOR
participant "AddApptCommand" as AddApptCommand LOGIC_COLOR
participant "CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "Model" as Model MODEL_COLOR
participant "AddressBook" as AddressBook MODEL_COLOR
participant "appt:Appointment" as Appt MODEL_COLOR
participant "edited:Person" as Person MODEL_COLOR
end box

box UI UI_COLOR_T1
participant "AppointmentListPanel" as ApptListPanel UI_COLOR
end box

user -[USER_COLOR]> Logic : addAppt command
activate Logic LOGIC_COLOR

Logic -[LOGIC_COLOR]> AddApptCommand : execute
activate AddApptCommand LOGIC_COLOR

AddApptCommand -[LOGIC_COLOR]> Model : fetchPersonIfPresent()
activate Model MODEL_COLOR
Model -[MODEL_COLOR]-> AddApptCommand : target
deactivate Model MODEL_COLOR

AddApptCommand -[LOGIC_COLOR]> AddApptCommand : createEditedPerson(target)
activate AddApptCommand LOGIC_COLOR_T1

create Appt MODEL_COLOR
AddApptCommand -[LOGIC_COLOR]> Appt : Name, Date, Time
activate Appt MODEL_COLOR
Appt -[MODEL_COLOR]-> AddApptCommand
deactivate Appt

create Person MODEL_COLOR
AddApptCommand -[LOGIC_COLOR]> Person : appt
activate Person MODEL_COLOR
Person -[MODEL_COLOR]-> AddApptCommand
deactivate Person
AddApptCommand -[LOGIC_COLOR]-> AddApptCommand : edited
deactivate AddApptCommand LOGIC_COLOR_T1
AddApptCommand -[LOGIC_COLOR]> Model : setPerson(target, edited)
activate Model MODEL_COLOR
Model -[MODEL_COLOR]-> AddApptCommand
deactivate Model MODEL_COLOR

AddApptCommand -[LOGIC_COLOR]> Model : update ListView filters
activate Model MODEL_COLOR
Model -[UI_COLOR]-> ApptListPanel : Listener triggered
activate ApptListPanel UI_COLOR
ApptListPanel -[UI_COLOR]> ApptListPanel : refresh ListView
ApptListPanel -[UI_COLOR]-> Model
deactivate ApptListPanel UI_COLOR

Model -[MODEL_COLOR]-> AddApptCommand
deactivate Model MODEL_COLOR

create CommandResult LOGIC_COLOR
AddApptCommand -[LOGIC_COLOR]> CommandResult : Success
activate CommandResult LOGIC_COLOR
CommandResult -[LOGIC_COLOR]> AddApptCommand : r
deactivate CommandResult LOGIC_COLOR

AddApptCommand -[LOGIC_COLOR]> Logic : r
deactivate AddApptCommand LOGIC_COLOR

Logic -[LOGIC_COLOR]> user : r
destroy AddApptCommand
deactivate Logic LOGIC_COLOR
@enduml
