@startuml
'https://plantuml.com/activity-diagram-beta
<style>
activityDiagram {
  FontSize 40
  FontStyle bold

  activity {
    BackgroundColor #ffffff
    BorderColor #33668E
    FontColor #000000
    FontName arial
    FontSize 30
  }

  diamond {
    BackgroundColor yellow
    LineColor #000000
    FontColor green
    FontName arial
    FontSize 15
  }

  arrow {
    FontColor green
    FontName arial
    FontSize 30
    FontStyle bold
  }

  partition {
     BackgroundColor #e6f7ff
     FontColor #003366
     LineColor #33668E
     FontName arial                // Sets the font style
     FontSize 30
     RoundCorner 10
     Bold true
   }
}
document {
   BackgroundColor transparent
}
</style>

|#f5e58c|UiManager|
start
:Accept user input command;
|#C8C8FA|LogicManager|
:Execute the input;
:Parse the input;
if () then ([invalid command format])
    |UiManager|
    :Show MESSAGE_INVALID_COMMAND_FORMAT;
    stop
    |LogicManager|
else ([else])
    :Parse the arguments;
    if () then ([invalid arg format])
        |UiManager|
        :Show MESSAGE_USAGE
        of AddCommand;
        stop
    else ([else])
        |LogicManager|
        :Create an
        AddCommand object;
        :Execute
        AddCommand;
        |#F97181|ModelManager|
        :Create a student to be added;
        :Check duplicates;
        if () then ([is duplicate])
            |UiManager|
            :Show MESSAGE_DUPLICATE;
            stop
        else ([else])
            |ModelManager|
            :Add the student
            to the address book;
            :Update the filtered list;
            :Check clashing schedules;
            if () then ([have clashes])
                |UiManager|
                :Show MESSAGE_HAS_CLASHES;
            else ([else])
            endif
            :Show MESSAGE_SUCCESS
            of AddCommand;
            stop
        endif
endif

@enduml
