@startuml
hide circle
skinparam classAttributeIconSize 0

Class "{abstract}\nCommand" as Command {
  +execute(Model): CommandResult
}
Class AddFCommand {
  +COMMAND_WORD: String
  +MESSAGE_SUCCESS: String
  +MESSAGE_DUPLICATE_PATIENT: String
  +toAdd: Patient
  +execute(Model): CommandResult
}
Class CommandException

AddFCommand -up-|> Command
Command ..> CommandException: throws >
AddFCommand .right.> CommandException: throws >
@enduml
