@startuml

|User|
start
:Add student command entered;
|System|
if (Is Command format valid?) then (no)
    |User|
    :Receive error message;
else (yes)
    |System|
    :Parse command parameters;
    :Create Student object;
    if (Is Duplicate student or Student ID?) then (yes)
        |User|
        :Receive error message;
    else (no)
        if (Tutorial exists?) then (yes)
            :Add student to address book;
            :Assign to tutorial;
            |User|
            :Receive success message;
        else (no)
            |User|
            :Receive tutorial not found message;
        endif
    endif
endif

stop

@enduml
