@startuml
!include style.puml
skinparam ArrowFontStyle plain
skinparam sequenceReferenceBackgroundColor lightgrey

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":AddGuestCommandParser" as AddGuestCommandParser LOGIC_COLOR
participant "a:AddGuestCommand" as AddGuestCommand LOGIC_COLOR
end box

[-> LogicManager : execute(C)
activate LogicManager

LogicManager -> AddressBookParser : parseCommand(C)
activate AddressBookParser

create AddGuestCommandParser
AddressBookParser -> AddGuestCommandParser
activate AddGuestCommandParser

AddGuestCommandParser --> AddressBookParser
deactivate AddGuestCommandParser

AddressBookParser -> AddGuestCommandParser : parse(C, excluding the add_guest part in front)
activate AddGuestCommandParser

ref over AddGuestCommandParser
   create Guest object and AddGuestCommand object
end ref

AddGuestCommandParser --> AddressBookParser : AddGuestCommand obj
deactivate AddGuestCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
AddGuestCommandParser -[hidden]-> AddressBookParser
destroy AddGuestCommandParser

AddressBookParser --> LogicManager : AddGuestCommand obj
deactivate AddressBookParser

LogicManager -> AddGuestCommand : execute(m)
activate AddGuestCommand

ref over AddGuestCommand
    execute add guest command
end ref

AddGuestCommand --> LogicManager : CommandResult obj
deactivate AddGuestCommand

[<--LogicManager : CommandResult obj
deactivate LogicManager
@enduml
