@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":AddCommandParser" as AddCommandParser LOGIC_COLOR
participant "<<class>>\nArgumentTokenizer" as ArgumentTokenizer LOGIC_COLOR
participant "argMultimap:ArgumentMultiMap" as ArgumentMultiMap LOGIC_COLOR
participant "<<class>>\nParserUtil" as ParserUtil LOGIC_COLOR
end box

AddCommandParser -> ParserUtil : parseName(...)
activate ParserUtil

ParserUtil --> AddCommandParser
deactivate ParserUtil

AddCommandParser -> ParserUtil : parseNric(...)
activate ParserUtil

ParserUtil --> AddCommandParser
deactivate ParserUtil

AddCommandParser -> ParserUtil : parseSex(...)
activate ParserUtil

ParserUtil --> AddCommandParser
deactivate ParserUtil

AddCommandParser -> ParserUtil : parseBirthDate(...)
activate ParserUtil

ParserUtil --> AddCommandParser
deactivate ParserUtil

AddCommandParser -> ParserUtil : parsePhone(...)
activate ParserUtil


ParserUtil --> AddCommandParser
deactivate ParserUtil

@enduml
