@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":RemarkCommandParser" as RemarkCommandParser LOGIC_COLOR
participant "a:AddRemarkCommand" as AddRemarkCommand LOGIC_COLOR
participant "r:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "m:Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("remark 1 -a Good progress")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("remark 1 -a Good progress")
activate AddressBookParser

create RemarkCommandParser
AddressBookParser -> RemarkCommandParser
activate RemarkCommandParser

RemarkCommandParser --> AddressBookParser
deactivate RemarkCommandParser

AddressBookParser -> RemarkCommandParser : parse("-a Good progress")
activate RemarkCommandParser

create AddRemarkCommand
RemarkCommandParser -> AddRemarkCommand
activate AddRemarkCommand

AddRemarkCommand --> RemarkCommandParser :
deactivate AddRemarkCommand

RemarkCommandParser --> AddressBookParser : a
deactivate RemarkCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
RemarkCommandParser -[hidden]-> AddressBookParser
destroy RemarkCommandParser

AddressBookParser --> LogicManager : a
deactivate AddressBookParser

LogicManager -> AddRemarkCommand : execute(m)
activate AddRemarkCommand

AddRemarkCommand -> Model : updateFilteredPersonList(true)
activate Model

Model --> AddRemarkCommand
deactivate Model

create CommandResult
AddRemarkCommand -> CommandResult
activate CommandResult

CommandResult --> AddRemarkCommand
deactivate CommandResult

AddRemarkCommand --> LogicManager : r
deactivate AddRemarkCommand

[<--LogicManager
deactivate LogicManager
@enduml
