@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":VersionedClientHub" as VersionedClientHub MODEL_COLOR
end box

[-> Model : undoClientHub()
activate Model

Model -> VersionedClientHub : undo()
activate VersionedClientHub

VersionedClientHub -> VersionedClientHub :resetData(ReadOnlyClientHub)
VersionedClientHub --> Model :
deactivate VersionedClientHub

[<-- Model
deactivate Model

@enduml
