@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":VersionedAddressBook" as VersionedAddressBook MODEL_COLOR
participant ":UniquePersonList" as UniquePersonList MODEL_COLOR
end box

[-> Model : addPerson(Person person)
activate Model

Model -> VersionedAddressBook : addPerson(Person person)
activate VersionedAddressBook
VersionedAddressBook -> UniquePersonList : add(Person p)
activate UniquePersonList
UniquePersonList --> VersionedAddressBook
deactivate UniquePersonList

VersionedAddressBook --> Model
deactivate VersionedAddressBook

[<-- Model
deactivate Model

@enduml
