@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":ClientBookParser" as ClientBookParser LOGIC_COLOR
participant ":AddSellerCommandParser" as AddSellerCommandParser LOGIC_COLOR
participant "s:AddSellerCommand" as AddSellerCommand LOGIC_COLOR
participant "r:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "m:Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("addseller n/Mary p/83456789 e/mary@gmail.com")
activate LogicManager

LogicManager -> ClientBookParser : parseCommand("addseller n/Mary p/83456789 e/mary@gmail.com")
activate ClientBookParser

create AddSellerCommandParser
ClientBookParser -> AddSellerCommandParser
activate AddSellerCommandParser

AddSellerCommandParser --> ClientBookParser
deactivate AddSellerCommandParser

ClientBookParser -> AddSellerCommandParser : parse("Mary", "83456789", "mary@gmail.com")
activate AddSellerCommandParser

create AddSellerCommand
AddSellerCommandParser -> AddSellerCommand
activate AddSellerCommand

AddSellerCommand --> AddSellerCommandParser
deactivate AddSellerCommand

AddSellerCommandParser --> ClientBookParser : s
deactivate AddSellerCommandParser

ClientBookParser --> LogicManager : s
deactivate ClientBookParser

LogicManager -> AddSellerCommand : execute(m)
activate AddSellerCommand

AddSellerCommand -> Model : addSeller(name, phoneNumber, email)
activate Model

Model --> AddSellerCommand
deactivate Model

create CommandResult
AddSellerCommand -> CommandResult
activate CommandResult

CommandResult --> AddSellerCommand
deactivate CommandResult

AddSellerCommand --> LogicManager : r
deactivate AddSellerCommand

[<--LogicManager
deactivate LogicManager
@enduml
