@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":AddressBook" as AddressBook MODEL_COLOR
participant ":UniqueStudentList" as UniqueStudentList MODEL_COLOR
end box

[-> Model : hasStudent(student)
activate Model

Model -> AddressBook : hasStudent(student)
activate AddressBook


AddressBook -> UniqueStudentList : contains(student)
activate UniqueStudentList
UniqueStudentList --> AddressBook : Whether student exists
deactivate UniqueStudentList

AddressBook --> Model : Whether student exists
deactivate AddressBook
[<-- Model
deactivate Model

group opt[hasStudent is false]
    [-> Model : addStudent(student)
    activate Model

    Model -> AddressBook : addStudent(student)
    activate AddressBook

    AddressBook -> UniqueStudentList : add(student)
    activate UniqueStudentList

    [<-- Model
    deactivate UniqueStudentList
    deactivate AddressBook
    deactivate Model

    [-> Model : getClashingStudents(student)
    activate Model

    Model -> AddressBook : getClashingStudents(student)
    activate AddressBook

    AddressBook -> UniqueStudentList : getClashingStudents(student)
    activate UniqueStudentList
    UniqueStudentList --> AddressBook : List of clashing students
    deactivate UniqueStudentList

    AddressBook --> Model : List of clashing students
    deactivate AddressBook
    [<-- Model
    deactivate Model
end


@enduml
