@startuml
!include style.puml
skinparam ArrowFontStyle plain
skinparam ArrowColor blue

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":AddCommandParser" as AddCommandParser LOGIC_COLOR
participant "a:AddCommand" as AddCommand LOGIC_COLOR
participant "r:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "m:Model" as Model MODEL_COLOR
end box

box STORAGE STORAGE_COLOR_T1
participant ":Storage" as JsonAddressBookStorage STORAGE_COLOR
end box

[-> LogicManager : execute("add n/John ct/work p/98765432")

note left of LogicManager
We'll henceforth refer to
the parameter part
 (i.e. "n/John ct/work p/98765432")
 of the command as [parameters]
end note

activate LogicManager

LogicManager -> AddressBookParser : parseCommand("add [parameters]")
activate AddressBookParser

create AddCommandParser
AddressBookParser -> AddCommandParser
activate AddCommandParser

AddCommandParser --> AddressBookParser
deactivate AddCommandParser

AddressBookParser -> AddCommandParser : parse([parameters])
activate AddCommandParser

AddCommandParser -> Model
activate Model

Model --> AddCommandParser : p
deactivate Model

create AddCommand
AddCommandParser -> AddCommand : AddCommand(p)
activate AddCommand

AddCommand --> AddCommandParser : a
deactivate AddCommand

AddCommandParser --> AddressBookParser : a
deactivate AddCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
AddCommandParser -[hidden]-> AddressBookParser
destroy AddCommandParser

AddressBookParser --> LogicManager : a
deactivate AddressBookParser

LogicManager -> AddCommand : execute(model)
activate AddCommand

AddCommand -> Model : addPerson(person)
activate Model

Model --> AddCommand
deactivate Model

create CommandResult
AddCommand -> CommandResult
activate CommandResult

CommandResult --> AddCommand : r
deactivate CommandResult

AddCommand --> LogicManager : r
deactivate AddCommand

LogicManager -> JsonAddressBookStorage : saveAddressBook(model.getAddressBook())
activate JsonAddressBookStorage

JsonAddressBookStorage --> LogicManager
deactivate JsonAddressBookStorage

[<--LogicManager
deactivate LogicManager
@enduml
