@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":CampusConnectParser" as CampusConnectParser LOGIC_COLOR
participant ":AddTagCommandParser" as AddTagCommandParser LOGIC_COLOR
participant "a:AddTagCommand" as AddTagCommand LOGIC_COLOR
participant "r:CommandResult" as CommandResult LOGIC_COLOR
participant "m:Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("addTag 2 t/mate")
activate LogicManager

LogicManager -> CampusConnectParser : parseCommand("addTag 2 t/mate")
activate CampusConnectParser

create AddTagCommandParser
CampusConnectParser -> AddTagCommandParser
activate AddTagCommandParser

AddTagCommandParser --> CampusConnectParser
deactivate AddTagCommandParser

CampusConnectParser -> AddTagCommandParser: parse("2 t/mate")
activate AddTagCommandParser

create AddTagCommand
AddTagCommandParser -> AddTagCommand
activate AddTagCommand

AddTagCommand --> AddTagCommandParser :
deactivate AddTagCommand

AddTagCommandParser --> CampusConnectParser : addTagCommand
AddTagCommandParser -[hidden]-> CampusConnectParser
destroy AddTagCommandParser

CampusConnectParser --> LogicManager : addTagCommand
deactivate CampusConnectParser

LogicManager -> AddTagCommand : execute(m)
activate AddTagCommand

AddTagCommand -> Model : getFilteredPersonList()
activate Model

Model --> AddTagCommand : lastShownList
deactivate Model

AddTagCommand -> Model : get(index)
activate Model

Model --> AddTagCommand : personToEdit
deactivate Model

AddTagCommand -> AddTagCommand : createEditedPerson(personToEdit, addTagDescriptor)

AddTagCommand --> AddTagCommand : editedPerson

AddTagCommand -> Model : deletePerson(personToEdit)
activate Model

Model --> AddTagCommand
deactivate Model

AddTagCommand -> Model : insertPerson(editedPerson, index)
activate Model

Model --> AddTagCommand
deactivate Model

AddTagCommand -> Model : updateFilteredPersonList(PREDICATE_SHOW_ALL_PERSONS)
activate Model

Model --> AddTagCommand
deactivate Model

create CommandResult
AddTagCommand -> CommandResult
activate CommandResult

CommandResult --> AddTagCommand : r
deactivate CommandResult

AddTagCommand --> LogicManager
deactivate AddTagCommand

[<-- LogicManager
deactivate LogicManager
@enduml
