@startuml
skin rose
skinparam ActivityFontSize 16
skinparam ArrowFontSize 13
start
:User executes AddTaskCommand;
  if () then ([inputs are valid])
    :Get patient by index;
    :Create a new Task object;
    :Add task to patient's task list;
    :Display list of tasks;
  else ([inputs are invalid])
    :Show error message;
  endif

stop
@enduml
