@startuml
start
:User enters Apply Command;


If () then ([Command has invalid prefixes])
    :Throws ParseException;

    else ([else])


    If () then ([Command has duplicate prefixes])
    :Throws ParseException;

    else ([Command is valid])
        :Returns ApplyCommand object;
        :LogicManager calls ApplyCommand#execute();

        If () then ([Invalid index])
        :Throws CommandException;

        else ([else])
            :Add application to list;
            endif
        endif
    endif
stop
@enduml