@startuml ApptCommand
hide circle
skinparam classAttributeIconSize 0

Class "{abstract}\nCommand" as Command {
  +execute(Model): CommandResult
}
Class ApptCommand {
  +COMMAND_WORD: String
  +MESSAGE_APPT_SUCCESS: String
  +MESSAGE_PATIENT_NOT_FOUND: String
  +MESSAGE_DUPLICATE_APPT: String
  -dateTime: LocalDateTime
  -nric: Nric
  +execute(Model): CommandResult
}
Class CommandException

ApptCommand -up-|> Command
Command ..> CommandException: throws >
ApptCommand .right.> CommandException: throws >
@enduml
