@startuml
!include <office/Concepts/globe_internet>
!include <office/Concepts/documents>
!include <office/Users/user>
!include style.puml

top to bottom direction

Class "<$user>" as User MODEL_COLOR_T2

Package "spleetwaise.commons" <<Rectangle>> {
    Class commons_Main #grey

    together {
        Class commons_Logic LOGIC_COLOR
        Class commons_Storage STORAGE_COLOR
        Class commons_UI UI_COLOR
        Class commons_Model MODEL_COLOR
    }

}

together {
    Package "spleetwaise.aB" <<Rectangle>> {
        Class aB_UI UI_COLOR
        Class aB_Logic LOGIC_COLOR
        Class aB_Storage STORAGE_COLOR
        Class aB_Model MODEL_COLOR
    }

    Package "spleetwaise.txn" <<Rectangle>> {
        Class txn_UI UI_COLOR
        Class txn_Logic LOGIC_COLOR
        Class txn_Storage STORAGE_COLOR
        Class txn_Model MODEL_COLOR
    }
}

Class "<$documents>" as File UI_COLOR_T1

commons_UI -[#green].> commons_Logic
commons_UI -right[#green].> commons_Model
commons_Logic -[#blue].> commons_Storage
commons_Logic -down[#blue].> commons_Model
commons_Main -[#grey].> commons_UI
commons_Main -[#grey].> commons_Logic
commons_Main -[#grey].> commons_Storage
commons_Main -up[#grey].> commons_Model
commons_Storage -down[STORAGE_COLOR].> File
User -down.> commons_UI

commons -down.> aB
commons -down.> txn
@enduml
