@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant "u:ArchiveCommand" as ArchiveCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box
[-> LogicManager : execute("archive 1")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("archive 1"))
activate AddressBookParser

create ArchiveCommand
AddressBookParser -> ArchiveCommand
activate ArchiveCommand

ArchiveCommand --> AddressBookParser
deactivate ArchiveCommand

AddressBookParser --> LogicManager : u
deactivate AddressBookParser

LogicManager -> ArchiveCommand : execute()
activate ArchiveCommand

ArchiveCommand -> Model : updateFilteredPersonList()
activate Model

Model --> ArchiveCommand
deactivate Model

ArchiveCommand --> LogicManager : result
deactivate ArchiveCommand
ArchiveCommand -[hidden]-> LogicManager : result
destroy ArchiveCommand

[<--LogicManager
deactivate LogicManager
@enduml
