@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":EventToryParser" as EventToryParser LOGIC_COLOR
participant ":AssignCommandParser" as AssignCommandParser LOGIC_COLOR
participant "a:AssignCommand" as AssignCommand LOGIC_COLOR
participant "r:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "m:Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("assign 1")
activate LogicManager

LogicManager -> EventToryParser : parseCommand("assign 1")
activate EventToryParser

create AssignCommandParser
EventToryParser -> AssignCommandParser
activate AssignCommandParser

AssignCommandParser --> EventToryParser
deactivate AssignCommandParser

EventToryParser -> AssignCommandParser : parse("1")
activate AssignCommandParser

create AssignCommand
AssignCommandParser -> AssignCommand
activate AssignCommand

AssignCommand --> AssignCommandParser : a
deactivate AssignCommand

AssignCommandParser --> EventToryParser : a
deactivate AssignCommandParser
destroy AssignCommandParser

EventToryParser --> LogicManager : a
deactivate EventToryParser

LogicManager -> AssignCommand : execute(m)
activate AssignCommand

AssignCommand -> Model : getUiState()

alt viewing Vendor Details
    AssignCommand -> Model : getViewedVendor()
    AssignCommand -> Model : resolveEvent(selectedIndex)

    opt vendor already assigned to event
        AssignCommand --> LogicManager : CommandException(MESSAGE_VENDOR_ALREADY_ASSIGNED_TO_EVENT)
    end
    AssignCommand -> Model : assignVendorToEvent(vendor, event)
else viewing Event Details
    AssignCommand -> Model : getViewedEvent()
    AssignCommand -> Model : resolveVendor(selectedIndex)

    opt event already contains vendor
        AssignCommand --> LogicManager : CommandException(MESSAGE_EVENT_ALREADY_ASSIGNED_TO_VENDOR)
    end
    AssignCommand -> Model : assignVendorToEvent(vendor, event)
else invalid view
    AssignCommand -> LogicManager : CommandResult(MESSAGE_ASSIGN_FAILURE_INVALID_VIEW)
end

create CommandResult
AssignCommand -> CommandResult
activate CommandResult

CommandResult --> AssignCommand
deactivate CommandResult

AssignCommand --> LogicManager : r
deactivate AssignCommand

[<--LogicManager
deactivate LogicManager
@enduml
