@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

AddressBook *-right-> "1" PersonList
AddressBook *-right-> "1" UniqueTagList
UniqueTagList -[hidden]down- PersonList
UniqueTagList -[hidden]down- PersonList

UniqueTagList -right-> "*" Tag
PersonList -right-> Person

Person -up-> "*" Tag

Person *--> "1" Name
Person *--> "1" Phone
Person *--> "0..1" Email
Person *--> "0..1" Address
Person *--> "0..1" Notes
Person *--> "0..1" Income
Person *--> "0..1" Age
@enduml
