@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

AddressBook *-right-> "1" UniquePersonList
AddressBook *-down-> "1" UniqueProjectList
AddressBook *-down-> "1" UniqueAssignmentList
AddressBook *-right-> "1" UniqueTagList
AddressBook *-right-> "1" UniqueSkillList
UniqueAssignmentList -[hidden]left- UniqueProjectList
UniqueTagList -[hidden]down- UniquePersonList
UniqueTagList -[hidden]down- UniquePersonList
UniqueSkillList -[hidden]down- UniqueTagList
Tag -[hidden]right- Skill

UniqueTagList -right-> "*" Tag
UniqueSkillList -right-> "*" Skill
UniquePersonList -right-> Person

Person -up-> "*" Tag
Person -up-> "*" Skill

Person *--> EmployeeId
Person *--> Name
Person *--> Phone
Person *--> Email
Person *--> Address

UniqueProjectList --> Project

Project *--> ProjectName
Project *--> ProjectId

UniqueAssignmentList --> Assignment

Assignment *--> AssignmentId
@enduml
