@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

PawPatrol *-right-> "1" UniqueOwnerList
PawPatrol *-right-> "1" UniqueTagList
UniqueTagList -[hidden]down- UniqueOwnerList
UniqueTagList -[hidden]down- UniqueOwnerList

UniqueTagList -right-> "*" Tag
UniqueOwnerList -right-> Owner

Owner -up-> "*" Tag

Owner *--> Name
Owner *--> Phone
Owner *--> Email
Owner *--> Address
@enduml
