@startuml
title Buyer Class Diagram

abstract class Person {
    - name: Name
    - phone: Phone
    - email: Email
    - appointment: Appointment
    - tags: Set<Tag>
    - remark: String
    + getRole(): Role
}

class Buyer {
    - role: Role = Role.BUYER
    + getRole(): Role
}

class Name {
    - fullName: String
}

class Phone {
    - value: String
}

class Email {
    - value: String
}

class Appointment {
    - date: Date
    - from: From
    - to: To
}

class Tag {
    - tagName: String
}

enum Role {
    BUYER
    SELLER
}

Person *-- Name : Composition
Person *-- Phone : Composition
Person *-- Email : Composition
Person *-- Appointment : Composition
Person *-- Tag : Composition
Buyer --|> Person
Buyer --> Role : Association

@enduml
