@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":ClearCommandParser" as ClearCommandParser LOGIC_COLOR
participant "c:ClearCommand" as ClearCommand LOGIC_COLOR
participant "r:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "m:Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("clear ...")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("clear ...")
activate AddressBookParser

create ClearCommandParser
AddressBookParser -> ClearCommandParser
activate ClearCommandParser

ClearCommandParser --> AddressBookParser
deactivate ClearCommandParser

alt "confirm is present
    AddressBookParser -> ClearCommandParser : parse("confirm")
    activate ClearCommandParser
    create ClearCommand
    ClearCommandParser -> ClearCommand
    activate ClearCommand
    ClearCommand --> ClearCommandParser
    deactivate ClearCommand

    ClearCommandParser --> AddressBookParser : c
    deactivate ClearCommandParser
    'Hidden arrow to position the destroy marker below the end of the activation bar.
    ClearCommandParser -[hidden]-> AddressBookParser
    destroy ClearCommandParser

    AddressBookParser --> LogicManager : c
    deactivate AddressBookParser

    LogicManager -> ClearCommand : execute(m)
    activate ClearCommand

    ClearCommand -> Model : setAddressBook(new AddressBook())
    activate Model

    Model --> ClearCommand
    deactivate Model

    create CommandResult
    ClearCommand -> CommandResult
    activate CommandResult

    CommandResult --> ClearCommand
    deactivate CommandResult

    ClearCommand --> LogicManager : r
    deactivate ClearCommand

else "confirm"\n is missing
    'Add a hidden arrow to adjust the position of the deactivation
    ClearCommandParser -[hidden]-> AddressBookParser
    AddressBookParser -> ClearCommandParser : parse(...)
    activate AddressBookParser
    activate ClearCommandParser
    ClearCommandParser -> AddressBookParser : throws ParseException
    deactivate ClearCommandParser
    AddressBookParser -> LogicManager : throws ParseException
    deactivate AddressBookParser
end

[<--LogicManager
deactivate LogicManager
@enduml
