@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12
start
:User types command;
:System parses the command;
:Creates a new Person object;
if () then ([Person does not already exist])
  :Add person to AddressBook;
else ([Person already exists])
  :Show error message;
endif
stop
@enduml

