@startuml

skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12

start
:User makes an action;
switch()
case ([press up button])
    if () then ([currentCommandIndex > 0])
        :CommandTextHistory \ngets previous command;
    else ([else])
    endif
case ([press down button])
    if () then ([currentCommandIndex \n        < size - 1])
        :CommandTextHistory
        gets next command;
    else ([else])
    endif
case ([enters new command])
    :CommandTextHistory
    adds new command;
    :CommandTextHistory sets
    currentCommandIndex to current size;
endswitch
stop

@enduml
