@startuml
skin rose
skinparam ActivityFontSize 16
skinparam ArrowFontSize 13
start
:User executes command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([command commits HRHelper])
    :Purge redundant states;
    :Save HRHelper to
    HRHelperStateList;
else ([else])
endif
stop
@enduml
