@startuml
'https://plantuml.com/activity-diagram-beta

start
:User types a command input;
if () then ([CommandHistory exists])
  :User input command is added to CommandHistory;
else ([else])
:KonTActs creates an new CommandHistory;
endif


stop

@enduml
