@startuml
skin rose
skinparam ActivityFontSize 14
skinparam ArrowFontSize 13
start
:User executes command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([command commits AddressBook])
    :Purge redundant states;
    :Save AddressBook to
    addressBookStateList;
elseif () then ([command commits WeddingBook])
    : Purge redundant states;
    : Save WeddingBook to
    weddingBookStateList;
else ([else])

endif
stop
@enduml
