@startuml
'https://plantuml.com/activity-diagram-beta

start
:User types a command input;
if () then ([CommandHistory exists])

else ([else])
:KonTActs creates a new CommandHistory;
endif

:User input command is added to CommandHistory;


stop

@enduml
