@startuml
!include style.puml
skinparam arrowThickness 1.1

package Logic as LogicPackage {
Class "<<interface>>\nLogic" as Logic LOGIC_COLOR
Class LogicManager LOGIC_COLOR
}

package Model as ModelPackage {
Class "<<interface>>\nModel" as Model MODEL_COLOR
Class ModelManager MODEL_COLOR
}

package Storage as StoragePackage {
Class "<<interface>>\nStorage" as Storage STORAGE_COLOR
Class StorageManager STORAGE_COLOR
}

Class HiddenOutside #FFFFFF
HiddenOutside -right-> Logic : <<uses>>

LogicManager .up.|> Logic LOGIC_COLOR_T4
ModelManager .up.|> Model MODEL_COLOR_T4
StorageManager .up.|> Storage STORAGE_COLOR_T4

LogicManager --> Model LOGIC_COLOR_T4
LogicManager --> Storage LOGIC_COLOR_T4
@enduml
