@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Class Course
Class CourseCode
Class CourseName
Class UniqueCourseList
Class "<<interface>>\nIterable" as Iterable
Class ObservableList

UniqueCourseList .up.|> Iterable
UniqueCourseList -up-|> ObservableList
UniqueCourseList --> "*" Course
Course *--> "1" CourseCode
Course *--> "1" CourseName

@enduml
