@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":ViewStudentCommandParser" as ViewStudentCommandParser LOGIC_COLOR
participant "v:ViewStudentCommand" as ViewStudentCommand LOGIC_COLOR
participant "r:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "m:Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("view Diddy")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("delete 1")
activate AddressBookParser

create ViewStudentCommandParser
AddressBookParser -> ViewStudentCommandParser
activate ViewStudentCommandParser

ViewStudentCommandParser --> AddressBookParser
deactivate ViewStudentCommandParser

AddressBookParser -> ViewStudentCommandParser : parse("1")
activate ViewStudentCommandParser

create ViewStudentCommand
ViewStudentCommandParser -> ViewStudentCommand
activate ViewStudentCommand

ViewStudentCommand --> ViewStudentCommandParser :
deactivate ViewStudentCommand

ViewStudentCommandParser --> AddressBookParser : d
deactivate ViewStudentCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
ViewStudentCommandParser -[hidden]-> AddressBookParser
destroy ViewStudentCommandParser

AddressBookParser --> LogicManager : d
deactivate AddressBookParser

LogicManager -> ViewStudentCommand : execute(m)
activate ViewStudentCommand

ViewStudentCommand -> Model : deletePerson(1)
activate Model

Model --> ViewStudentCommand
deactivate Model

create CommandResult
ViewStudentCommand -> CommandResult
activate CommandResult

CommandResult --> ViewStudentCommand
deactivate CommandResult

ViewStudentCommand --> LogicManager : r
deactivate ViewStudentCommand

[<--LogicManager
deactivate LogicManager
@enduml
