@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":DeleteCommandParser" as DeleteCommandParser LOGIC_COLOR
participant "d:DeleteCommand" as DeleteCommand LOGIC_COLOR
participant ":ParseException" as ParseException LOGIC_COLOR
participant ":ParserUtil" as ParserUtil LOGIC_COLOR
end box

[-> LogicManager : execute("delete 1")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("delete 1")
activate AddressBookParser

create DeleteCommandParser
AddressBookParser -> DeleteCommandParser
activate DeleteCommandParser

DeleteCommandParser --> AddressBookParser
deactivate DeleteCommandParser

AddressBookParser -> DeleteCommandParser : parse(arg)
activate DeleteCommandParser

create ParserUtil
DeleteCommandParser -> ParserUtil : parseIndexes(arg)
activate ParserUtil
ParserUtil --> DeleteCommandParser : List<Index> (indices)
deactivate ParserUtil

alt Single index in list
    DeleteCommandParser -> DeleteCommand : new DeleteCommand(indices)
    activate DeleteCommand
    DeleteCommand --> DeleteCommandParser : d
    deactivate DeleteCommand
else Multiple indices
    loop For each index starting from second
        alt Indices are duplicate
            DeleteCommandParser -> ParseException : throw ParseException("Indices must be unique")
            deactivate DeleteCommandParser
        end
    end
    DeleteCommandParser -> DeleteCommand : new DeleteCommand(indices)
    activate DeleteCommand
    DeleteCommand --> DeleteCommandParser : d
    deactivate DeleteCommand
end

DeleteCommandParser --> AddressBookParser : d
deactivate DeleteCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
DeleteCommandParser -[hidden]-> AddressBookParser
destroy DeleteCommandParser

AddressBookParser --> LogicManager : d
deactivate AddressBookParser

LogicManager -> DeleteCommand : execute(model)
activate DeleteCommand

ref over DeleteCommand : Execute delete command

DeleteCommand --> LogicManager : result
deactivate DeleteCommand
DeleteCommand -[hidden]-> LogicManager
destroy DeleteCommand

[<-- LogicManager : result
deactivate LogicManager
@enduml
