
@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":DeleteCommandParser" as DeleteCommandParser LOGIC_COLOR
participant "d:DeleteCommand" as DeleteCommand LOGIC_COLOR
participant "p:PrefixHandler" as PrefixHandler LOGIC_COLOR
participant "r:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "pred:FilterListPredicate" as FilterListPredicate MODEL_COLOR
participant "m:Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("delete n/John")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("delete prefix/attribute")
activate AddressBookParser

create DeleteCommandParser
AddressBookParser -> DeleteCommandParser
activate DeleteCommandParser

DeleteCommandParser --> AddressBookParser
deactivate DeleteCommandParser

AddressBookParser -> DeleteCommandParser : parse("prefix/attribute")
activate DeleteCommandParser

create NameContainsKeywordsPredicate
DeleteCommandParser -> NameContainsKeywordsPredicate
activate NameContainsKeywordsPredicate

NameContainsKeywordsPredicate --> DeleteCommandParser
deactivate NameContainsKeywordsPredicate

create DeleteCommand
DeleteCommandParser -> DeleteCommand : DeleteCommand(attribute)
activate DeleteCommand

DeleteCommand --> DeleteCommandParser : d
deactivate DeleteCommand

DeleteCommandParser --> AddressBookParser : d
deactivate DeleteCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
DeleteCommandParser -[hidden]-> AddressBookParser
destroy DeleteCommandParser

AddressBookParser --> LogicManager : d
deactivate AddressBookParser

LogicManager -> DeleteCommand : execute(m)
activate DeleteCommand

create PrefixHandler
DeleteCommand -> PrefixHandler
activate PrefixHandler

PrefixHandler --> DeleteCommand
deactivate PrefixHandler


DeleteCommand -> PrefixHandler : findPersonByAttribute(lastShownList, attribute)
activate PrefixHandler

PrefixHandler --> DeleteCommand : personsToDelete
deactivate PrefixHandler

alt One Match Found
    DeleteCommand -> Model : deletePerson(attribute)
    activate Model
    Model --> DeleteCommand
    deactivate Model
end

alt Multiple Matches Found
    create FilterListPredicate
    DeleteCommand -> FilterListPredicate : personsToDelete
    activate FilterListPredicate

    FilterListPredicate --> DeleteCommand
    deactivate FilterListPredicate

    DeleteCommand -> Model : updateFilteredPersonList(pred)
    activate Model

    Model --> DeleteCommand : Filtered List
    deactivate Model

end

create CommandResult
DeleteCommand -> CommandResult
activate CommandResult

CommandResult --> DeleteCommand
deactivate CommandResult

DeleteCommand --> LogicManager : r
deactivate DeleteCommand


[<--LogicManager
deactivate LogicManager
@enduml
