@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":DeleteStudentCommandParser" as DeleteStudentCommandParser LOGIC_COLOR
participant "d:DeleteStudentCommand" as DeleteStudentCommand LOGIC_COLOR
participant "r:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "m:Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("del_s sno/A0234567H")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("del_s sno/A0234567H")
activate AddressBookParser

create DeleteStudentCommandParser
AddressBookParser -> DeleteStudentCommandParser : parse("sno/A0234567H")
activate DeleteStudentCommandParser

create DeleteStudentCommand
DeleteStudentCommandParser -> DeleteStudentCommand : parse("sno/A0234567H")
activate DeleteStudentCommand

DeleteStudentCommand --> DeleteStudentCommandParser : d
deactivate DeleteStudentCommand

DeleteStudentCommandParser --> AddressBookParser : d
deactivate DeleteStudentCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
DeleteStudentCommandParser -[hidden]-> AddressBookParser
destroy DeleteStudentCommandParser

AddressBookParser --> LogicManager : d
deactivate AddressBookParser

LogicManager -> DeleteStudentCommand : execute(m)
activate DeleteStudentCommand

DeleteStudentCommand -> Model : deleteStudent(student)
activate Model

Model --> DeleteStudentCommand
deactivate Model

create CommandResult
DeleteStudentCommand -> CommandResult : new CommandResult(message)
activate CommandResult

CommandResult --> DeleteStudentCommand
deactivate CommandResult
destroy CommandResult

DeleteStudentCommand --> LogicManager : r
deactivate DeleteStudentCommand
destroy DeleteStudentCommand

[<-- LogicManager
deactivate LogicManager
@enduml
