@startuml
title Delete Activity Diagram
start
:Delete command is given;
if () then ([index within range])
    :User is prompted
    for confirmation;
    if () then ([User confirms])
        :Delete contact
        at specified index;
    else ([else])
        :Show command
        cancelled message;
    endif
 else ([else])
    :Show error message;
 endif

stop
@enduml
