@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":EditGuestCommandParser" as EditGuestCommandParser LOGIC_COLOR
participant "d:EditGuestDescriptor" as EditGuestDescriptor LOGIC_COLOR
participant "e:EditGuestCommand" as EditGuestCommand LOGIC_COLOR
participant "r:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "editedGuest:Guest" as Guest MODEL_COLOR
participant "m:Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("edit_guest 1 n/Amy")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("edit_guest 1 n/Amy")
activate AddressBookParser

create EditGuestCommandParser
AddressBookParser -> EditGuestCommandParser
activate EditGuestCommandParser

EditGuestCommandParser --> AddressBookParser
deactivate EditGuestCommandParser

AddressBookParser -> EditGuestCommandParser : parse("1 n/Amy")
activate EditGuestCommandParser

create EditGuestDescriptor
EditGuestCommandParser -> EditGuestDescriptor
activate EditGuestDescriptor

EditGuestDescriptor --> EditGuestCommandParser : d
deactivate EditGuestDescriptor

create EditGuestCommand
EditGuestCommandParser -> EditGuestCommand : new EditGuestCommand(index, d)
activate EditGuestCommand

EditGuestCommand --> EditGuestCommandParser : e
deactivate EditGuestCommand

EditGuestCommandParser --> AddressBookParser : e
deactivate EditGuestCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
EditGuestCommandParser -[hidden]-> AddressBookParser
destroy EditGuestCommandParser

AddressBookParser --> LogicManager : e
deactivate AddressBookParser

LogicManager -> EditGuestCommand : execute(m)
activate EditGuestCommand

EditGuestCommand -> Model : getFilteredGuestList()
activate Model

Model --> EditGuestCommand : filteredGuestList
deactivate Model

EditGuestCommand -> EditGuestCommand : createEditedGuest(guestToEdit, e)
activate EditGuestCommand

create Guest
EditGuestCommand -> Guest
activate Guest

Guest --> EditGuestCommand : editedGuest
deactivate Guest
return editedGuest

EditGuestCommand -> Model : setPerson(guestToEdit, editedGuest)
activate Model

Model --> EditGuestCommand
deactivate Model

EditGuestCommand -> Model : updateFilteredPersonList(predicate)
activate Model

Model --> EditGuestCommand
deactivate Model

create CommandResult
EditGuestCommand -> CommandResult
activate CommandResult

CommandResult --> EditGuestCommand : r
deactivate CommandResult

EditGuestCommand --> LogicManager : r
deactivate EditGuestCommand

[<--LogicManager
deactivate LogicManager
@enduml
