@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":EditCommandParser" as EditCommandParser LOGIC_COLOR
participant "<<class>>\n:EditCommand" as EditCommandClass LOGIC_COLOR
participant "command:EditCommand" as EditCommand LOGIC_COLOR
participant "commandResult:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "model:Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("edit 1 n/Samson")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("edit 1 n/Samson")
activate AddressBookParser

create EditCommandParser
AddressBookParser -> EditCommandParser
activate EditCommandParser

EditCommandParser --> AddressBookParser
deactivate EditCommandParser

AddressBookParser -> EditCommandClass : EditStudentDescriptor()
activate EditCommandClass

EditCommandClass --> AddressBookParser : editStudentDescriptor
deactivate EditCommandClass

AddressBookParser -> EditCommandParser : parse("1")
activate EditCommandParser

create EditCommand
EditCommandParser -> EditCommand
activate EditCommand

EditCommand --> EditCommandParser :
deactivate EditCommand

EditCommandParser --> AddressBookParser : command
deactivate EditCommandParser

'Hidden arrow to position the destroy marker below the end of the activation bar.
EditCommandParser -[hidden]-> AddressBookParser
destroy EditCommandParser

AddressBookParser --> LogicManager : command
deactivate AddressBookParser

LogicManager -> EditCommand : execute(model)
activate EditCommand

EditCommand -> Model : editStudent()
activate Model

Model --> EditCommand
deactivate Model

create CommandResult
EditCommand -> CommandResult
activate CommandResult

CommandResult --> EditCommand
deactivate CommandResult

EditCommand --> LogicManager : commandResult
deactivate EditCommand

[<--LogicManager
deactivate LogicManager
@enduml
