@startuml
'https://plantuml.com/class-diagram

class ContactablePerson
class Person
class EmergencyOnlyContact

ContactablePerson <|--- Person
ContactablePerson <|--- EmergencyOnlyContact


ContactablePerson : phone
ContactablePerson : name
@enduml
