@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

EmergencyContact *--> "1"Name
EmergencyContact *--> "1"Phone
EmergencyContact *--> "1"Relationship

@enduml
