@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12
start
:User executes export command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

:Contacts in DorManagerPro exported to save file in data folder;

stop
@enduml
