@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":FavCommandParser" as FavCommandParser LOGIC_COLOR
participant "f:FavCommand" as FavCommand LOGIC_COLOR
participant "r:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "m:Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("fav 1")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("fav 1")
activate AddressBookParser

create FavCommandParser
AddressBookParser -> FavCommandParser
activate FavCommandParser

FavCommandParser --> AddressBookParser
deactivate FavCommandParser

AddressBookParser -> FavCommandParser : parse("1")
activate FavCommandParser

create FavCommand
FavCommandParser -> FavCommand
activate FavCommand

FavCommand --> FavCommandParser :
deactivate FavCommand

FavCommandParser --> AddressBookParser : f
deactivate FavCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
FavCommandParser -[hidden]-> AddressBookParser
destroy FavCommandParser

AddressBookParser --> LogicManager : f
deactivate AddressBookParser

LogicManager -> FavCommand : execute(m)
activate FavCommand

FavCommand -> Model : favcompany(1)
activate Model

Model --> FavCommand
deactivate Model

create CommandResult
FavCommand -> CommandResult
activate CommandResult

CommandResult --> FavCommand
deactivate CommandResult

FavCommand --> LogicManager : r
deactivate FavCommand

[<-- LogicManager
deactivate LogicManager
@enduml
