@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":FilterCommandParser" as FilterCommandParser LOGIC_COLOR
participant "s:StatusPredicate" as StatusPredicate LOGIC_COLOR
participant "f:FilterCommand" as FilterCommand LOGIC_COLOR
participant "r:CommandResult" as CommandResult LOGIC_COLOR

end box

box Model MODEL_COLOR_T1
participant "m:Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("/filter " + status)
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("/filter " + status)
activate AddressBookParser

create FilterCommandParser
AddressBookParser -> FilterCommandParser
activate FilterCommandParser

FilterCommandParser --> AddressBookParser
deactivate FilterCommandParser

AddressBookParser -> FilterCommandParser : parse(status)
activate FilterCommandParser

create StatusPredicate
FilterCommandParser -> StatusPredicate
activate StatusPredicate

StatusPredicate --> FilterCommandParser
deactivate StatusPredicate

create FilterCommand
FilterCommandParser -> FilterCommand :
activate FilterCommand

FilterCommand --> FilterCommandParser :
deactivate FilterCommand

FilterCommandParser --> AddressBookParser : f
deactivate FilterCommandParser

'Hidden arrow to position the destroy marker below the end of the activation bar.
FilterCommandParser -[hidden]-> AddressBookParser
destroy FilterCommandParser

AddressBookParser --> LogicManager : f
deactivate AddressBookParser

LogicManager -> FilterCommand : execute(m)
activate FilterCommand

FilterCommand -> Model : updateFilteredList(s)
activate Model

Model --> FilterCommand
deactivate Model

create CommandResult
FilterCommand -> CommandResult
activate CommandResult

CommandResult --> FilterCommand
deactivate CommandResult

FilterCommand --> LogicManager : r
deactivate FilterCommand

[<--LogicManager : r
deactivate LogicManager
destroy FilterCommand
destroy StatusPredicate
@enduml
