@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":FindCommand" as FindCommand LOGIC_COLOR
participant "CommandResult" as CommandResult LOGIC_COLOR
participant "Messages" as Messages LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box


[-> FindCommand : execute(model)
activate FindCommand

FindCommand -> Model : updateFilteredPersonList(predicate)
activate Model
Model --> FindCommand
deactivate Model

FindCommand -> Model : sortByPin()
activate Model
deactivate Model

FindCommand -> Model : getFilteredPersonList()
activate Model
Model --> FindCommand : list
deactivate Model

FindCommand -> FindCommand : list.size()

FindCommand -> Messages : String.format(MESSAGE_PERSONS_LISTED_OVERVIEW, list size)
activate Messages
Messages --> FindCommand : formatted message
deactivate Messages

create CommandResult
FindCommand -> CommandResult : new CommandResult(formatted message)
activate CommandResult
CommandResult --> FindCommand : result
deactivate CommandResult

[<-- FindCommand : result
deactivate FindCommand

@enduml
