@startuml
start

:User inputs "find" command with keywords;
:Create FindCommand with NameContainsKeywordsPredicate;

:Execute FindCommand;
:requireNonNull(model);

if (model is null) then (no)
    :Throw NullPointerException;
else (yes)
    :model.updateFilteredPersonList(predicate);
    :Retrieve the size of model.getFilteredPersonList();
    :Format message with number of persons listed;
    :Return CommandResult with formatted message;
endif

:End of execute method;

stop
@enduml
