@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":FindCommand" as FindCommand LOGIC_COLOR
participant "CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box


[-> FindCommand : execute(model)
activate FindCommand

FindCommand -> Model : updateFilteredPersonList(predicate)
activate Model
Model --> FindCommand
deactivate Model

FindCommand -> Model : sortByPin()
activate Model
deactivate Model

FindCommand -> Model : getFilteredPersonList()
activate Model
Model --> FindCommand : list
deactivate Model

create CommandResult
FindCommand -> CommandResult : new CommandResult(...)
activate CommandResult
CommandResult --> FindCommand : result
deactivate CommandResult

[<-- FindCommand : result
deactivate FindCommand

@enduml
