@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant "h:HelpCommand" as HelpCommand LOGIC_COLOR
participant "r:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "m:Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("/help")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("/help")
activate AddressBookParser

create HelpCommand
AddressBookParser -> HelpCommand
activate HelpCommand

HelpCommand --> AddressBookParser :
deactivate HelpCommand

AddressBookParser --> LogicManager : h
deactivate AddressBookParser

LogicManager -> HelpCommand : execute(m)
activate HelpCommand

create CommandResult
HelpCommand -> CommandResult
activate CommandResult

CommandResult --> HelpCommand
deactivate CommandResult

HelpCommand --> LogicManager : r
deactivate HelpCommand

[<--LogicManager : r
deactivate LogicManager
'Hidden arrow to position the destroy marker below the end of the activation bar.
HelpCommand -[hidden]-> LogicManager
destroy HelpCommand
@enduml
