@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":ImportCommandParser" as ImportCommandParser LOGIC_COLOR
participant "i:ImportCommand" as ImportCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "m:Model" as Model MODEL_COLOR
end box

box Storage STORAGE_COLOR_T1
participant "s:Storage" as Storage STORAGE_COLOR
end box

[-> LogicManager : execute("import fp/./data/SaveFile3.json")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("import fp/./data/SaveFile3.json")
activate AddressBookParser

create ImportCommandParser
AddressBookParser -> ImportCommandParser
activate ImportCommandParser

ImportCommandParser --> AddressBookParser
deactivate ImportCommandParser

AddressBookParser -> ImportCommandParser : parse("fp/./data/SaveFile3.json")
activate ImportCommandParser

create ImportCommand
ImportCommandParser -> ImportCommand
activate ImportCommand

ImportCommand --> ImportCommandParser :
deactivate ImportCommand

ImportCommandParser --> AddressBookParser : i
deactivate ImportCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
ImportCommandParser -[hidden]-> AddressBookParser
destroy ImportCommandParser

AddressBookParser --> LogicManager : i
deactivate AddressBookParser

LogicManager -> ImportCommand : execute(m, s)
activate ImportCommand

ImportCommand -> Storage : readAddressBook(filePath)
activate Storage

Storage --> ImportCommand : addressBookOptional
deactivate Storage

ImportCommand -> Model : setAddressBook(addressBookOptional)
activate Model

Model --> ImportCommand
deactivate Model

ImportCommand --> LogicManager : result

LogicManager -> Model : pushToUndoStack(i)
activate Model

Model --> LogicManager
deactivate Model

[<--LogicManager
deactivate LogicManager
@enduml
