@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LinkCommand" as LinkCommand LOGIC_COLOR
participant "CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LinkCommand : execute(model)
activate LinkCommand


LinkCommand -> Model : personFromName(...)
activate Model
Model --> LinkCommand : child
deactivate Model

LinkCommand -> Model : personFromName(...)
activate Model
Model --> LinkCommand : parent
deactivate Model


LinkCommand -> Model : createLinkedChild(castedChild, castedParent)
activate Model
Model --> LinkCommand : linkedChild
deactivate Model

LinkCommand -> Model : createLinkedParent(castedParent, castedChild)
activate Model
Model --> LinkCommand : linkedParent
deactivate Model

LinkCommand -> Model : setPerson(castedChild, linkedChild)
activate Model
deactivate Model

LinkCommand -> Model : setPerson(castedParent, linkedParent)
activate Model
deactivate Model

create CommandResult
LinkCommand -> CommandResult : new CommandResult(...)
activate CommandResult
CommandResult --> LinkCommand : result
deactivate CommandResult

[<-- LinkCommand : result
deactivate LinkCommand
@enduml
