@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Command <|-- ListCommand

ListCommand <|-- ListPersonCommand
ListCommand <|-- ListProjectCommand
ListCommand <|-- ListProjectMembersCommand
ListCommand <|-- ListAssignmentsCommand

@enduml
