@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12
start
:User executes listt command;
:Model updates person list;
:GUI displays transactions list;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([deletet or summary command])
    :Model updates transaction list;
    :GUI displays transactions list;
else ([else])
    if () then ([list command])
        :Model clears transactions list;
        :Model updates person list;
        :GUI displays person list;
    else ([other commands])
        :Exception thrown;
    endif
endif

stop
@enduml
