@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000
skinparam ClassBackgroundColor #FFFFAA

title After Command "archive pa/archiveFile1.json"

package data as DataPkg {
    class State1 as "<u>addressBook.json:File</u>"
}

package archive as ArchivePkg {
    class State2 as "<u>archiveFile1.json:File</u>"
}


class Pointer1 as "Current working addressBook\n Containing data from archiveFile1.json" #FFFFFF
Pointer1 -up-> State1
note right on link: The original data in this file \n will be discarded.

@end
