@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR_T4
skinparam classBackgroundColor LOGIC_COLOR

package Logic as LogicPackage {
class "<<interface>>\nLogic" as Logic
class LogicManager


package "Parser classes" as ParserPackage {
  class "AddressBookParser" as ABParser
}

package "Command classes" as CommandPackage {
  class CommandResult
  class "{abstract}\nCommand" as Command
}

}

package "Model" as ModelPackage {
  class "<<interface>>\nModel" as Model
}
package "Storage" as StoragePackage {
  class "<<interface>>\nStorage" as Storage
}

LogicManager .u.|> Logic
LogicManager --> "1" ABParser
LogicManager --> "1" Model
LogicManager --> "1" Storage
LogicManager -- CommandResult : > returns
ABParser -- Command : > creates
Command -- CommandResult : > creates
Model -- Storage : > save to

note left of Command: Command = AddCommand, \nFindCommand, etc

class Outside #FFFFFF

Outside .d.> Logic

@enduml
