@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model as ModelPackage <<Rectangle>>{
Class "<<interface>>\nReadOnlyAddressBook" as ReadOnlyAddressBook
Class "<<interface>>\nReadOnlyUserPrefs" as ReadOnlyUserPrefs
Class "<<interface>>\nModel" as Model
Class AddressBook
Class ModelManager
Class UserPrefs

Class ActiveTags

Class UniqueWeddingList
Class Wedding
Class WeddingName
Class WeddingDate

Class UniquePersonList
Class Person
Class PersonId
Class Address
Class Email
Class Name
Class Phone
Class Tag

Class I #FFFFFF
}

Class HiddenOutside #FFFFFF

HiddenOutside ..> Model

AddressBook .up.|> ReadOnlyAddressBook

ModelManager .up.|> Model
Model .right.> ReadOnlyUserPrefs
Model .left.> ReadOnlyAddressBook
ModelManager -left-> "1" AddressBook
ModelManager -right-> "1" UserPrefs
ModelManager -down-> "1" ActiveTags
UserPrefs .up.|> ReadOnlyUserPrefs

AddressBook *-down-> "1" UniquePersonList
AddressBook *-down-> "1" UniqueWeddingList
UniquePersonList ---> "~* all" Person
UniqueWeddingList ---> "~* all" Wedding
Person *-right-> "1" PersonId
Person *--> "1" Name
Person *--> "1" Phone
Person *--> "1" Email
Person *--> "1" Address
Person *--> "*" Tag

ActiveTags ----> "~* active" Tag

Wedding *--left--> "*" PersonId
Wedding --> "1" WeddingName
Wedding --> "1" WeddingDate

Person -[hidden]up--> I
UniquePersonList -[hidden]right-> I

ModelManager --> "~* filtered" Wedding
ModelManager ---> "~* filtered" Person

Name -[hidden]right-> Phone
Phone -[hidden]right-> Address
Address -[hidden]right-> Email

@enduml
