@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

package Model as ModelPackage <<Rectangle>> {
  class "<<interface>>\nReadOnlyAddressBook" as ReadOnlyAddressBook
  class "<<interface>>\nReadOnlyUserPrefs" as ReadOnlyUserPrefs
  class "<<interface>>\nModel" as Model
  class AddressBook
  class ModelManager
  class UserPrefs

  class UniqueList
  class InternshipApplication

  class Status <<enumeration>> {
    PENDING
    ACCEPTED
    REJECTED
  }
  class Email
  class Name
  class Date
  class Company
  class Role

  class I #FFFFFF

}

class HiddenOutside #FFFFFF
HiddenOutside ..> Model

AddressBook .up.|> ReadOnlyAddressBook

ModelManager .up.|> Model
Model .right.> ReadOnlyUserPrefs
Model .left.> ReadOnlyAddressBook
ModelManager -left-> "1" AddressBook
ModelManager -right-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

AddressBook *--> "1" UniqueList
UniqueList --> "~* all" InternshipApplication
InternshipApplication *--> Date
InternshipApplication *--> Status
InternshipApplication *--> Company
InternshipApplication *--> Role

Company *--> Name
Company *--> Email

InternshipApplication -[hidden]up--> I
UniqueList -[hidden]right-> I

Name -[hidden]right-> Date
Date -[hidden]right-> Status
Status -[hidden]right-> Email

ModelManager --> "~* filtered" InternshipApplication
@enduml
