@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model as ModelPackage <<Rectangle>>{
Class "<<interface>>\nReadOnlyAddressBook" as ReadOnlyAddressBook
Class "<<interface>>\nReadOnlyUserPrefs" as ReadOnlyUserPrefs
Class "<<interface>>\nModel" as Model
Class AddressBook
Class ModelManager
Class UserPrefs

Class UniqueStudentList
Class Student
Class Email
Class Name
Class Phone
Class Course

Class UniqueConsultList
Class Consultation
Class Date
Class Time

Class UniqueLessonList
Class Lesson
Class StudentLessonInfo
Class Attendance
Class Participation

Class I #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

AddressBook .up.|> ReadOnlyAddressBook

ModelManager .up.|> Model
Model .right.> ReadOnlyUserPrefs
Model .left.> ReadOnlyAddressBook
ModelManager -left-> "1" AddressBook
ModelManager -right-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

AddressBook *--> "1" UniqueStudentList
UniqueStudentList --> "~* all" Student
Student *--> Name
Student *--> Phone
Student *--> Email
Student *--> "0..*" Course

AddressBook *--> "1" UniqueConsultList
UniqueConsultList --> "~* all" Consultation
Consultation *--> Date
Consultation *--> Time
Consultation -down--> "0..*" Student

AddressBook *--> "1" UniqueLessonList
UniqueLessonList --> "~* all" Lesson
Lesson *--> Date
Lesson *--> Time
Lesson -down--> "0..*" StudentLessonInfo

StudentLessonInfo -left-> "1" Student
StudentLessonInfo -down-> Attendance
StudentLessonInfo -down-> Participation

Student -[hidden]up--> I
UniqueStudentList -[hidden]right-> I
UniqueConsultList -[hidden]left-> I
UniqueLessonList -[hidden]right-> I

ModelManager -right--> "~* filtered" Student
ModelManager --> "~* filtered" Consultation
ModelManager -right--> "~* filtered" Lesson
@enduml
