@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR_T4
skinparam classBackgroundColor LOGIC_COLOR

package "Parser Command SubClasses"{

Class "<<interface>>\nParser" as Parser
Class AddCommandParser
Class DeleteCommandParser
Class EditCommandParser
Class FindCommandParser
Class ListCommandParser
Class NoteCommandParser
Class SortCommandParser
Class StarCommandParser
Class UnstarCommandParser


AddCommandParser -up-|> Parser
DeleteCommandParser -up---|> Parser
EditCommandParser -up--|> Parser
FindCommandParser -up---|> Parser
ListCommandParser -up--|> Parser
NoteCommandParser -up---|> Parser
SortCommandParser -up--|> Parser
StarCommandParser -up---|> Parser
UnstarCommandParser -up-|> Parser

}


@enduml

