@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR_T4
skinparam classBackgroundColor LOGIC_COLOR
skinparam linetype ortho
skinparam nodesep 150

package "Parser classes" {
  class "<<interface>>\nParser" as Parser
  class XYZCommandParser
  class AddressBookParser
  class ArgumentTokenizer
  class ArgumentMultimap
  class CliSyntax
  class ParserUtil
  class Prefix
}

XYZCommandParser .up.|> Parser
AddressBookParser -left- XYZCommandParser : > creates

class "{abstract}\nCommand" as Command
class XYZCommand
XYZCommand .up.|> Command

AddressBookParser -u- XYZCommand: > "\ncreates and returns"

ArgumentTokenizer -u- XYZCommandParser : < uses
ArgumentTokenizer -l- ArgumentMultimap : > returns
XYZCommandParser -l ArgumentMultimap : > uses

CliSyntax -u-- XYZCommandParser : < uses
ParserUtil -u- XYZCommandParser : < "uses\n"
Prefix <-l-- CliSyntax : < contains
Prefix -l-- ArgumentTokenizer : < maps

Class HiddenOutside #FFFFFF
HiddenOutside .d..> AddressBookParser

@enduml
