@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR_T4
skinparam classBackgroundColor LOGIC_COLOR

Class "{abstract}\nCommand" as Command
Class XYZCommand

package "Parser classes"{
Class "<<interface>>\nParser" as Parser
Class TutorEaseParser
Class ContactCommandParser
Class LessonCommandParser
Class XYZContactCommandParser
Class XYZLessonCommandParser
Class CliSyntax
Class ParserUtil
Class ArgumentMultimap
Class ArgumentTokenizer
Class Prefix
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> TutorEaseParser

XYZCommand -up-|> Command
XYZContactCommand -up-|> Command
XYZLessonCommand -up-|> Command

TutorEaseParser .down.> ContactCommandParser: <<create>>
TutorEaseParser .down.> LessonCommandParser: <<create>>
ContactCommandParser .down.> XYZContactCommandParser: <<create>>
LessonCommandParser .down.> XYZLessonCommandParser: <<create>>


XYZContactCommandParser ..> XYZContactCommand : <<create>>
XYZLessonCommandParser ..> XYZLessonCommand : <<create>>
TutorEaseParser ..> Command : <<use>>

ContactCommandParser .up.|> Parser
LessonCommandParser .up.|> Parser
XYZContactCommandParser .up.|> Parser
XYZContactCommandParser ..> ArgumentMultimap
XYZContactCommandParser ..> ArgumentTokenizer
XYZLessonCommandParser .up.|> Parser
XYZLessonCommandParser ..> ArgumentMultimap
XYZLessonCommandParser ..> ArgumentTokenizer

ArgumentTokenizer .left.> ArgumentMultimap
XYZContactCommandParser ..> CliSyntax
XYZLessonCommandParser ..> CliSyntax

CliSyntax ..> Prefix
XYZContactCommandParser ..> ParserUtil
XYZLessonCommandParser ..> ParserUtil

ParserUtil .down.> Prefix
ArgumentTokenizer .down.> Prefix
@enduml
