@startuml

package Model as ModelPackage<<Rectangle>>{
hide circle
skinparam classAttributeIconSize 0
    class Student

    class Tutorial
    class Participation

    Participation *-- Attendance

    Student "0..*" -right- "0..*" Tutorial
    (Student, Tutorial). Participation
}

@enduml
