@startuml
|User|
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12
start
:Check for password file;

if () then ([File exists])
    :Prompt user for existing password;
    repeat
        :Input password;
        :Verify password;
    repeat while () is ([Access Denied])
    :Grant access;
else ([File does not exist])
    :Prompt user for a new password;
    :Input new password;
    :Save new password;
endif

stop
@enduml
