@startuml
|User|
start
:Check for password file;

if (File exists?) then (yes)
    repeat
        :Prompt user for existing password;
        :Input password;
        :Verify password;
    repeat while (Access denied?) is (no)
        :Grant access;

else (no)
    :Prompt user for a new password;
    :Input new password;
    :Save new password;
endif

stop
@enduml
