@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package "" as ModelPackage <<Rectangle>>{
Class Patient
Class Nric
Class Name
Class Sex
Class BirthDate
Class ApptList
Class Phone
Class Email
Class Address
Class AllergyList
Class Allergy
Class BloodType
Class HealthRisk
Class ExistingCondition
Class Note
Class Appt
Class HealthService

Class I #FFFFFF
}

Class HiddenOutside #FFFFFF

Patient *-down-> "1" Name
Patient *-down-> "1" Nric
Patient *-down-> "1" Sex
Patient *-down-> "1" BirthDate
Patient *-down-> "1" Phone
Patient *-down-> "1" ApptList
Patient *-down-> "1" Email
Patient *-down-> "1" Address
Patient *-down-> "1" AllergyList
Patient *-down-> "1" BloodType
Patient *-down-> "1" HealthRisk
Patient *-down-> "1" ExistingCondition
Patient *-down-> "1" Note
ApptList *-down-> "*" Appt
Appt *-down-> "1" HealthService
AllergyList *-down-> "*" Allergy
@enduml
