@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR


Person *--> "1"Name
Person *--> "1"Phone
Person *--> "1"Email
Person *-->  "*"EmergencyContact
Person *-->  "1"Doctor
Person *--> "1"Address
Person *--> "*" Tag

@enduml
