@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":PinCommand" as PinCommand LOGIC_COLOR
participant "result:CommandResult" as CommandResult LOGIC_COLOR
participant ":CommandException" as CommandException LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
    participant ":Model" as Model MODEL_COLOR
end box

[-> PinCommand : execute(model)
activate PinCommand

PinCommand -> Model : getFilteredPersonList()
activate Model
Model --> PinCommand : lastShownList
deactivate Model

loop For each index in targetIndices
    PinCommand -> PinCommand : Check index is within bounds
    alt Index out of bounds
        PinCommand -> CommandException : throw CommandException()

    end

    PinCommand -> Model : pinPerson(person)
    activate Model
    deactivate Model


end

PinCommand -> Model : sortByPin()
activate Model
deactivate Model

alt One person pinned
    PinCommand -> CommandResult : new CommandResult(MESSAGE_PIN_PERSON_SUCCESS)
    activate CommandResult
    CommandResult --> PinCommand : result
    deactivate CommandResult
else Multiple people pinned
    PinCommand -> CommandResult : new CommandResult(MESSAGE_PIN_PEOPLE_SUCCESS)
    activate CommandResult
    CommandResult --> PinCommand : result
    deactivate CommandResult
end

deactivate CommandResult

[<-- PinCommand : result
deactivate PinCommand

@enduml
