@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

UniquePropertyList -right-> Property

Property *--> LandlordName
Property *--> Location
Property *--> Phone
Property *--> PropertyType
Property *--> AskingPrice
@enduml
