@startuml
'https://plantuml.com/activity-diagram-beta

start
:user executes seed command;

repeat
if () then ([model.hasPerson()])
    :continue;
else ([else])
    :add person to model;
endif
repeat while () is ([end of for loop == false]) not ([else])
stop

@enduml
