@startuml
!include style.puml
skinparam ArrowFontStyle plain

box MainWindow UI_COLOR_T1
participant ":MainWindow" as MainWindow UI_COLOR
end box

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":ShowCommandParser" as ShowCommandParser LOGIC_COLOR
participant "d:ShowCommand" as ShowCommand LOGIC_COLOR
participant "r:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "m:Model" as Model MODEL_COLOR
end box

[-> MainWindow : executeCommand("show 1")
activate MainWindow

MainWindow -> LogicManager
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("show 1")
activate AddressBookParser

create ShowCommandParser
AddressBookParser -> ShowCommandParser
activate ShowCommandParser

ShowCommandParser --> AddressBookParser
deactivate ShowCommandParser

AddressBookParser -> ShowCommandParser : parse("1")
activate ShowCommandParser

create ShowCommand
ShowCommandParser -> ShowCommand
activate ShowCommand

ShowCommand --> ShowCommandParser :
deactivate ShowCommand

ShowCommandParser --> AddressBookParser : d
deactivate ShowCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
ShowCommandParser -[hidden]-> AddressBookParser
destroy ShowCommandParser

AddressBookParser --> LogicManager : d
deactivate AddressBookParser

LogicManager -> ShowCommand : execute(m)
activate ShowCommand

ShowCommand -> Model : getFilteredPersonList()
activate Model

Model --> ShowCommand
deactivate Model

create CommandResult
ShowCommand -> CommandResult
activate CommandResult

CommandResult --> ShowCommand
deactivate CommandResult

ShowCommand --> LogicManager : r
deactivate ShowCommand

LogicManager --> MainWindow : r
deactivate LogicManager

[<--MainWindow
deactivate MainWindow
@enduml
