@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant "d:SortCommand" as SortCommand LOGIC_COLOR
participant "r:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "m:Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("sort")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("sort")
activate AddressBookParser

create SortCommand
AddressBookParser -> SortCommand
activate SortCommand

SortCommand --> AddressBookParser :
deactivate SortCommand

AddressBookParser --> LogicManager : d
deactivate AddressBookParser

LogicManager -> SortCommand : execute(m)
activate SortCommand

SortCommand -> Model : updateSortedPersonList()
activate Model

Model --> SortCommand
deactivate Model

create CommandResult
SortCommand -> CommandResult
activate CommandResult

CommandResult --> SortCommand
deactivate CommandResult

SortCommand --> LogicManager : r
deactivate SortCommand

[<--LogicManager
deactivate LogicManager
@enduml
