@startuml
!include style.puml
skinparam ArrowFontStyle plain

start
:User wants to update the status of the internship application at index i;

switch ()
case ([User enters the command "/accept i"])
    if ( ) then ([Index is valid])
        :Update the internship application status to
        **ACCEPTED**;
    else ([else])
        :User receives an error message;
        stop
    endif
case ([User enters the command "/reject i"])
    if ( ) then ([Index is valid])
        :Update the internship application status to
        **REJECTED**;
    else ([else])
        :User receives an error message;
        stop
    endif
case ([User enters the command "/pending i"])
    if ( ) then ([Index is valid])
        :Update the internship application status to
        **PENDING**;
    else ([else])
        :User receives an error message;
        stop
    endif
endswitch

:User receives success message;
stop
@enduml
