@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

package Storage as StoragePackage {

package "UserPrefs Storage" #F4F6F6{
Class "<<interface>>\nUserPrefsStorage" as UserPrefsStorage
Class JsonUserPrefsStorage
}

Class "<<interface>>\nStorage" as Storage
Class StorageManager

package "ClientBook Storage" #F4F6F6{
Class "<<interface>>\nClientBookStorage" as ClientBookStorage
Class JsonClientBookStorage
Class JsonSerializableClientBook
Class JsonAdaptedClient
}

package "MeetingBook Storage" #F4F6F6{
Class "<<interface>>\nMeetingBookStorage" as MeetingBookStorage
Class JsonMeetingBookStorage
Class JsonSerializableMeetingBook
Class JsonAdaptedMeeting
}

package "PropertyBook Storage" #F4F6F6{
Class "<<interface>>\nPropertyBookStorage" as PropertyBookStorage
Class JsonPropertyBookStorage
Class JsonSerializablePropertyBook
Class JsonAdaptedProperty
}

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Storage

StorageManager .up.|> Storage
StorageManager -up-> "1" UserPrefsStorage
StorageManager -up-> "1" ClientBookStorage
StorageManager -up-> "1" MeetingBookStorage
StorageManager -up-> "1" PropertyBookStorage

Storage -left-|> UserPrefsStorage
Storage -right-|> ClientBookStorage
Storage -right-|> MeetingBookStorage
Storage -right-|> PropertyBookStorage

JsonUserPrefsStorage .up.|> UserPrefsStorage
JsonClientBookStorage .up.|> ClientBookStorage
JsonClientBookStorage ..> JsonSerializableClientBook
JsonSerializableClientBook --> "*" JsonAdaptedClient

JsonMeetingBookStorage .up.|> MeetingBookStorage
JsonMeetingBookStorage ..> JsonSerializableMeetingBook
JsonSerializableMeetingBook --> "*" JsonAdaptedMeeting

JsonPropertyBookStorage .up.|> PropertyBookStorage
JsonPropertyBookStorage ..> JsonSerializablePropertyBook
JsonSerializablePropertyBook --> "*" JsonAdaptedProperty

@enduml
