@startuml UiClassDiagram

!include style.puml
top to bottom direction
skinparam arrowThickness 1.1
skinparam classBackgroundColor UI_COLOR
skinparam classAttributeIconSize 0
skinparam CardFontColor White
skinparam CardBackgroundColor UI_COLOR
package "UI" <<Rectangle>> {
    Class Ui <<interface>>

    class UiManager {
        <color:#FFFFFF>-Logic logic
    }

    class MainWindow {
        <color:#FFFFFF>+handleHelpWindow()
        <color:#FFFFFF>+showPatientInfo(Patient patient)
        <color:#FFFFFF>+showAppts(TreeSet<FilteredAppointment> appts)
    }

    Class HelpWindow
    Class HelpKeywordWindow
    Class ResultDisplay
    Class PatientListPanel
    Class PatientCard

    class StatusBarFooter {

    }

    class CommandBox {

    }

    class FilteredApptListPanel {

    }

    class FilteredAppointmentCard {

    }

    class PatientInfoPanel {

    }

    class "{abstract}\nUiPart" {

    }
}

package Model <<Card>> {
}

package Logic <<Card>> {


}

package ExternalComponents <<Card>> {
}


ExternalComponents ..> Ui
Ui <|-.- UiManager
MainWindow --> Logic
UiManager --> Logic
UiManager --> "1" MainWindow
MainWindow *--> "1" CommandBox
MainWindow *--> "1" ResultDisplay
MainWindow *--> "0..1" PatientListPanel
MainWindow *--> "1" StatusBarFooter
MainWindow *--> "0..1" FilteredApptListPanel
MainWindow *--> "0..1" PatientInfoPanel
MainWindow --> "0..1" HelpWindow
MainWindow --> "0..1" HelpKeywordWindow
FilteredApptListPanel -down-> "*" FilteredAppointmentCard
PatientListPanel --> "*" PatientCard
MainWindow -.-> Model
PatientCard -.-> Model
PatientInfoPanel -.-> Model
FilteredAppointmentCard -.-> Model
"{abstract}\nUiPart" <|-up- CommandBox
"{abstract}\nUiPart" <|-up- ResultDisplay
"{abstract}\nUiPart" <|-up- PatientListPanel
"{abstract}\nUiPart" <|-up- StatusBarFooter
"{abstract}\nUiPart" <|-up- FilteredApptListPanel
"{abstract}\nUiPart" <|-up- PatientInfoPanel
"{abstract}\nUiPart" <|-up- PatientCard

@enduml
