@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classBackgroundColor UI_COLOR

package UI <<Rectangle>>{
Class "<<interface>>\nUi" as Ui
Class "{abstract}\nUiPart" as UiPart
Class UiManager
Class MainWindow
Class HelpWindow
Class ResultDisplay
Class PersonListPanel
Class PersonCard
Class CommandBox
Class WeddingCard
Class WeddingListPanel
Class ViewWeddingPanel
}

package Model <<Rectangle>> {
Class HiddenModel #FFFFFF
}

package Logic <<Rectangle>> {
Class HiddenLogic #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Ui

UiManager .left.|> Ui
UiManager -down-> "1" MainWindow
MainWindow *-down->  "1" CommandBox
MainWindow *-down-> "1" ResultDisplay
MainWindow *-down-> "1" PersonListPanel
MainWindow --> "0..1" HelpWindow
MainWindow *-down-> "1" WeddingListPanel
MainWindow *-down-> "1" ViewWeddingPanel

PersonListPanel -down-> "*" PersonCard
WeddingListPanel -down-> "*" WeddingCard

MainWindow -left-|> UiPart

ResultDisplay --|> UiPart
CommandBox --|> UiPart
PersonListPanel --|> UiPart
PersonCard --|> UiPart
HelpWindow --|> UiPart
WeddingCard --|> UiPart
WeddingListPanel --|> UiPart
ViewWeddingPanel --|> UiPart

PersonCard ..> Model
WeddingCard ..> Model
UiManager -right-> Logic
MainWindow -left-> Logic

PersonListPanel -[hidden]left- HelpWindow
HelpWindow -[hidden]left- CommandBox
CommandBox -[hidden]left- ResultDisplay

MainWindow -[hidden]-|> UiPart
@enduml
