@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000
skinparam ClassBackgroundColor #FFFFAA

title After undo

package Commands {
    class State1 as "<u>c0:Command</u>"
    class State2 as "<u>c1:Command</u>"
}
State1 -[hidden]right-> State2
@end
