@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":KeyContactsParser" as KeyContactsParser LOGIC_COLOR
participant "u:UndoCommand" as UndoCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box
[-> LogicManager : execute(undo)
activate LogicManager

LogicManager -> KeyContactsParser : parseCommand(undo)
activate KeyContactsParser

create UndoCommand
KeyContactsParser -> UndoCommand
activate UndoCommand

UndoCommand --> KeyContactsParser
deactivate UndoCommand

KeyContactsParser --> LogicManager : u
deactivate KeyContactsParser

LogicManager -> UndoCommand : execute()
activate UndoCommand

UndoCommand -> Model : undoStudentDirectory()
activate Model

Model --> UndoCommand
deactivate Model

UndoCommand --> LogicManager : result
deactivate UndoCommand
UndoCommand -[hidden]-> LogicManager : result
destroy UndoCommand

[<--LogicManager
deactivate LogicManager
@enduml
