@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":VersionedBuyerList" as VersionedBuyerList MODEL_COLOR
end box

[-> Model : undoBuyerList()
activate Model

Model -> VersionedBuyerList : undo()
activate VersionedBuyerList

VersionedBuyerList -> VersionedBuyerList :resetData(ReadOnlyBuyerList)
VersionedBuyerList --> Model :
deactivate VersionedBuyerList

[<-- Model
deactivate Model

@enduml
