@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000
skinparam ClassBackgroundColor #FFFFAA

title After command "c2"

package Commands <<rectangle>> {
    class State1 as "<u>c0:Command</u>"
    class State2 as "<u>c1:Command</u>"
    class State3 as "<u>c2:Command</u>"
}

State1 -[hidden]right-> State2
State2 -[hidden]right-> State3
@end
