@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant "u:UndoCommand" as UndoCommand LOGIC_COLOR
participant "ch:CommandHistory" as CommandHistory LOGIC_COLOR
participant "c:Command" as Command LOGIC_COLOR
end box

LogicManager -> AddressBookParser : parseCommand("undo")
activate AddressBookParser

create UndoCommand
AddressBookParser -> UndoCommand
activate UndoCommand

UndoCommand --> AddressBookParser
deactivate UndoCommand

AddressBookParser --> LogicManager : u
deactivate AddressBookParser

LogicManager -> UndoCommand : execute()
activate UndoCommand

UndoCommand -> CommandHistory : getCommandInputHistory()
activate CommandHistory

CommandHistory --> UndoCommand : lastestCommand
deactivate CommandHistory

UndoCommand -> Command : undo()
activate Command

Command --> UndoCommand : result
deactivate Command

UndoCommand --> LogicManager : result
deactivate UndoCommand

[<--LogicManager
deactivate LogicManager
@enduml
