@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000
skinparam ClassBackgroundColor #FFFFAA
skinparam ranksep 1

title After "c2"

package Commands <<rectangle>> {
    class State1 as "<u>c0:Command</u>"
    class State2 as "<u>c1:Command</u>"
    class State3 as "<u>c2:Command</u>"
}

State1 -[hidden]up-> State2
State2 -[hidden]up-> State3
@end
