@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AgentAssistParser" as AgentAssistParser LOGIC_COLOR
participant "u:UndoCommand" as UndoCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box
[-> LogicManager : execute(undo)
activate LogicManager

LogicManager -> AgentAssistParser : parseCommand(undo)
activate AgentAssistParser

create UndoCommand
AgentAssistParser -> UndoCommand
activate UndoCommand

UndoCommand --> AgentAssistParser
deactivate UndoCommand

AgentAssistParser --> LogicManager : u
deactivate AgentAssistParser

LogicManager -> UndoCommand : execute()
activate UndoCommand

UndoCommand -> Model : undoAgentAssist()
activate Model

Model --> UndoCommand
deactivate Model

UndoCommand --> LogicManager : result
deactivate UndoCommand
UndoCommand -[hidden]-> LogicManager : result
destroy UndoCommand

[<--LogicManager
deactivate LogicManager
@enduml
