@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":VersionedPrudy" as VersionedPrudy MODEL_COLOR
end box

[-> Model : undoPrudy()
activate Model

Model -> VersionedPrudy : undo()
activate VersionedPrudy

VersionedPrudy -> VersionedPrudy :resetData(ReadOnlyPrudy)
VersionedPrudy --> Model :
deactivate VersionedPrudy

[<-- Model
deactivate Model

@enduml
