@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":VersionedAcademyAssist" as VersionedAcademyAssist MODEL_COLOR
end box

[-> Model : undoAcademyAssist()
activate Model

Model -> VersionedAcademyAssist : undo()
activate VersionedAcademyAssist

VersionedAcademyAssist -> VersionedAcademyAssist :resetData(ReadOnlyAcademyAssist)
VersionedAcademyAssist --> Model :
deactivate VersionedAcademyAssist

[<-- Model
deactivate Model

@enduml
