@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000
skinparam ClassBackgroundColor #FFFFAA

title Initial state

package States {
    class State1 as "<u>ch:ClientHub</u>"
    class State2 as "<u>ch1:ClientHub</u>"
    class State3 as "<u>ch3:ClientHub</u>"
}
State1 -[hidden]right-> State2
State2 -[hidden]right-> State3
hide State2
hide State3

class Pointer as "Current State" #FFFFFF
Pointer -up-> State1
@end
