@startuml
'https://plantuml.com/activity-diagram-beta
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12

start
:User inputs add command;
'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.
while () is ([invalid input or is duplicate])
    :UGTeach shows error message;
    :User modifies input;
endwhile ([else])
:UGTeach adds student to the list;
if () then ([new schedule clashes])
    :UGTeach shows success message
            with clashing schedules;
else ([else])
    :UGTeach shows success message;
endif
stop

@enduml
