
@startuml
!define rect(x) rectangle x
skinparam monochrome true
skinparam defaultFontName Courier
skinparam node {
    BorderColor DarkRed
    FontSize 14
    FontColor DarkRed
    BackgroundColor #FFFFCC
    Shadowing true
}

start

:User enters a command;
:Parser parses the command;

if () then ([known command])
  if () then ([Exit])
    :Exit command is created;
    :Exit command is executed;
    :Application closes;
    stop
  else
    if  () then ([List])
      :List command is created;
      :List command is executed;
      :UI list all available clients;
      stop
    else ([action commands])
      :Parser processes relevant action command;
      if () then ([valid])
        :Command is created;
        :Command is executed;
        :UI shows respective success message;
        stop
      else ([invalid])
        :UI displays error message;
        stop
      endif
    endif
  endif
else ([unknown command])
  :UI displays invalid command;
  stop
endif

@enduml
