@startuml
!include ../style.puml
skinparam ArrowFontStyle plain

participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":TransactionBookParser" as TransactionBookParser LOGIC_COLOR
participant ":AddCommandParser" as AddCommandParser LOGIC_COLOR
participant "command:AddCommand" as AddCommand LOGIC_COLOR


[-> LogicManager : execute(commandText)
activate LogicManager

LogicManager -> AddressBookParser : parseCommand(commandText)
activate AddressBookParser

AddressBookParser --> LogicManager : null
deactivate AddressBookParser

LogicManager -> TransactionBookParser : parseCommand(commandText)
activate TransactionBookParser

create AddCommandParser
TransactionBookParser -> AddCommandParser : AddCommandParser()
activate AddCommandParser

AddCommandParser --> TransactionBookParser
deactivate AddCommandParser

TransactionBookParser -> AddCommandParser : parse(arguments)
activate AddCommandParser

create AddCommand
AddCommandParser -> AddCommand : AddCommand(transaction)
activate AddCommand

AddCommand --> AddCommandParser :
deactivate AddCommand

AddCommandParser --> TransactionBookParser : command
deactivate AddCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
AddCommandParser -[hidden]-> TransactionBookParser
destroy AddCommandParser

TransactionBookParser --> LogicManager : command
deactivate AddressBookParser

@enduml
