@startuml
!include ../style.puml
skinparam ArrowFontStyle plain

Participant ":LogicManager" as logic LOGIC_COLOR
Participant ":AddressBookParser" as abp LOGIC_COLOR
Participant ":TransactionBookParser" as tbp LOGIC_COLOR
Participant ":AddCommandParser" as acp LOGIC_COLOR
Participant ":command:AddCommand" as ac LOGIC_COLOR

[-> logic : execute
activate logic
logic -> abp ++: parseCommand(commandText)
abp --> logic --: null

logic -> tbp ++: parseCommand(commandText)
create acp
tbp -> acp
tbp -> acp ++: parse(arguments)
create ac
acp -> ac ++: transaction
ac --> acp --
acp --> tbp --: command
tbp --> logic --: command

@enduml
