@startuml
actor User
participant "MainWindow" as MW
participant "LogicManager" as LM
participant "AddressBookParser" as ABP
participant "g:AddGradeCommand" as OAGC
participant "ResultDisplay" as RD
participant "cr:CommandResult" as CR
participant ":Model" as M

/'
This diagram shows the normal flow of adding grade to a person's gradeList.
The flow assumes correct input from user.
'/

User -> MW: executeCommand("addGrade ...")
activate MW
MW -> LM: execute("addGrade ...")
activate LM
LM -> ABP: parseCommand("addGrade ...")
activate ABP
ABP -> OAGC
activate OAGC
OAGC --> ABP
deactivate OAGC
ABP --> LM: g
deactivate ABP
LM -> OAGC: execute()
activate OAGC
OAGC -> M: setPerson()
activate M
M --> OAGC
deactivate M
OAGC -> CR
activate CR
CR --> OAGC: cr
deactivate CR
OAGC --> LM: cr
deactivate OAGC
LM --> MW: cr
deactivate LM
MW -> RD: setFeedbackToUser(CR)
activate RD
RD --> MW: display feedback to user
deactivate RD
MW --> User: return CommandResult
deactivate MW
@enduml
