@startuml
hide circle
skinparam classAttributeIconSize 0

Class "{abstract}\nCommand" as Command {
  +execute(Model): CommandResult
}
Class TagCommand {
  +COMMAND_WORD: String
  +MESSAGE_USAGE: String
  +MESSAGE_TAG_PERSON_SUCCESS: String
  +MESSAGE_TAG_NOT_CREATED: String
  +MESSAGE_DUPLICATE_TAG: String
  -targetIndex: Index
  -tag: Tag
  +execute(Model): CommandResult
}
Class CommandException

TagCommand -up-|> Command
Command ..> CommandException: throws >
TagCommand .right.> CommandException: throws >
@enduml
